### ISSUE TITLE
ggev is considered as a scalar function

### ISSUE THREAD

**Issue by selvavm** [blas-lapack-rs/lapack#27] opened 2021-04-17 15:05 UTC
`ggev` has incorrect type. It is not a scalar function and this is related to https://github.com/blas-lapack-rs/lapacke/issues/2. I would like to fix this but having trouble on setting up. Could you explain the procedure for contribution. Thanks

I tried below command,
`./bin/generate.py --sys lapack-sys`

**Comment by selvavm** [comment] 2021-04-17 17:08
On further debugging, I think there is a compatibility issue with `lapack-sys` and the python script. I am able to modify the script to generate the `lib.rs` but on comparing with your crate's `lib.rs`, there are too many changes. Hence, please suggest `lapack-sys` which you are using.

**Comment by IvanUkhov** [comment] 2021-04-17 19:03
I have revisited the code-generating functionality. The problem is that `lapack-sys` has changed drastically since last time. More specifically, it was switched from hand-crafted code to `bindgen`. `bin/generate.sh` is now working, but it is scaringly a lot of changes.

**Comment by selvavm** [comment] 2021-04-17 21:09
Thanks. When I try to build with ndarray/linalg I am getting lot of errors.

**Comment by IvanUkhov** [comment] 2021-04-18 12:27
Fixed in #28.

**Closed by IvanUkhov** 2021-04-18 12:27 UTC
